AUCTIPUS_TREE = {}
AUCTIPUS_PATHS = {
    {LE_ITEM_CLASS_WEAPON},
    {LE_ITEM_CLASS_WEAPON, LE_ITEM_WEAPON_AXE1H},
    {LE_ITEM_CLASS_WEAPON, LE_ITEM_WEAPON_AXE2H},
    {LE_ITEM_CLASS_WEAPON, LE_ITEM_WEAPON_BOWS},
    {LE_ITEM_CLASS_WEAPON, LE_ITEM_WEAPON_GUNS},
    {LE_ITEM_CLASS_WEAPON, LE_ITEM_WEAPON_MACE1H},
    {LE_ITEM_CLASS_WEAPON, LE_ITEM_WEAPON_MACE2H},
    {LE_ITEM_CLASS_WEAPON, LE_ITEM_WEAPON_POLEARM},
    {LE_ITEM_CLASS_WEAPON, LE_ITEM_WEAPON_SWORD1H},
    {LE_ITEM_CLASS_WEAPON, LE_ITEM_WEAPON_SWORD2H},
    {LE_ITEM_CLASS_WEAPON, LE_ITEM_WEAPON_STAFF},
    {LE_ITEM_CLASS_WEAPON, LE_ITEM_WEAPON_UNARMED},
    {LE_ITEM_CLASS_WEAPON, LE_ITEM_WEAPON_GENERIC},
    {LE_ITEM_CLASS_WEAPON, LE_ITEM_WEAPON_DAGGER},
    {LE_ITEM_CLASS_WEAPON, LE_ITEM_WEAPON_THROWN},
    {LE_ITEM_CLASS_WEAPON, LE_ITEM_WEAPON_CROSSBOW},
    {LE_ITEM_CLASS_WEAPON, LE_ITEM_WEAPON_WAND},
    {LE_ITEM_CLASS_WEAPON, LE_ITEM_WEAPON_FISHINGPOLE},

    {LE_ITEM_CLASS_ARMOR},

    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_GENERIC},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_GENERIC, LE_INVENTORY_TYPE_HEAD_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_GENERIC, LE_INVENTORY_TYPE_NECK_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_GENERIC, LE_INVENTORY_TYPE_BODY_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_GENERIC, LE_INVENTORY_TYPE_FINGER_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_GENERIC, LE_INVENTORY_TYPE_TRINKET_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_GENERIC, LE_INVENTORY_TYPE_HOLDABLE_TYPE},

    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_CLOTH},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_CLOTH, LE_INVENTORY_TYPE_HEAD_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_CLOTH, LE_INVENTORY_TYPE_SHOULDER_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_CLOTH, LE_INVENTORY_TYPE_CHEST_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_CLOTH, LE_INVENTORY_TYPE_WAIST_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_CLOTH, LE_INVENTORY_TYPE_LEGS_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_CLOTH, LE_INVENTORY_TYPE_FEET_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_CLOTH, LE_INVENTORY_TYPE_WRIST_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_CLOTH, LE_INVENTORY_TYPE_HAND_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_CLOTH, LE_INVENTORY_TYPE_CLOAK_TYPE},

    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_LEATHER},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_LEATHER, LE_INVENTORY_TYPE_HEAD_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_LEATHER, LE_INVENTORY_TYPE_SHOULDER_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_LEATHER, LE_INVENTORY_TYPE_CHEST_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_LEATHER, LE_INVENTORY_TYPE_WAIST_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_LEATHER, LE_INVENTORY_TYPE_LEGS_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_LEATHER, LE_INVENTORY_TYPE_FEET_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_LEATHER, LE_INVENTORY_TYPE_WRIST_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_LEATHER, LE_INVENTORY_TYPE_HAND_TYPE},

    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_MAIL},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_MAIL, LE_INVENTORY_TYPE_HEAD_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_MAIL, LE_INVENTORY_TYPE_SHOULDER_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_MAIL, LE_INVENTORY_TYPE_CHEST_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_MAIL, LE_INVENTORY_TYPE_WAIST_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_MAIL, LE_INVENTORY_TYPE_LEGS_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_MAIL, LE_INVENTORY_TYPE_FEET_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_MAIL, LE_INVENTORY_TYPE_WRIST_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_MAIL, LE_INVENTORY_TYPE_HAND_TYPE},

    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_PLATE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_PLATE, LE_INVENTORY_TYPE_HEAD_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_PLATE, LE_INVENTORY_TYPE_SHOULDER_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_PLATE, LE_INVENTORY_TYPE_CHEST_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_PLATE, LE_INVENTORY_TYPE_WAIST_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_PLATE, LE_INVENTORY_TYPE_LEGS_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_PLATE, LE_INVENTORY_TYPE_FEET_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_PLATE, LE_INVENTORY_TYPE_WRIST_TYPE},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_PLATE, LE_INVENTORY_TYPE_HAND_TYPE},

    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_SHIELD},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_LIBRAM},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_IDOL},
    {LE_ITEM_CLASS_ARMOR, LE_ITEM_ARMOR_TOTEM},
}

local function GenerateAuctionPaths(classID)
    local subClassIDs = {GetAuctionItemSubClasses(classID)}
    table.insert(AUCTIPUS_PATHS, {classID})
    if #subClassIDs > 1 then
        for i, subClassID in ipairs(subClassIDs) do
            table.insert(AUCTIPUS_PATHS, {classID, subClassID})
        end
    end
end

GenerateAuctionPaths(LE_ITEM_CLASS_CONTAINER)
GenerateAuctionPaths(LE_ITEM_CLASS_CONSUMABLE)
GenerateAuctionPaths(LE_ITEM_CLASS_TRADEGOODS)
GenerateAuctionPaths(LE_ITEM_CLASS_PROJECTILE)
GenerateAuctionPaths(LE_ITEM_CLASS_QUIVER)
GenerateAuctionPaths(LE_ITEM_CLASS_RECIPE)
GenerateAuctionPaths(LE_ITEM_CLASS_GEM)
GenerateAuctionPaths(LE_ITEM_CLASS_MISCELLANEOUS)
GenerateAuctionPaths(LE_ITEM_CLASS_QUESTITEM)

local RENAME_TABLE = {
    ["Gem > Purple"] = "Gem > Purple [Red/Blue]",
    ["Gem > Green"]  = "Gem > Green [Yellow/Blue]",
    ["Gem > Orange"] = "Gem > Orange [Red/Yellow]",
}

function AuctipusGenPaths()
    local paths = {}
    for i, path in ipairs(AUCTIPUS_PATHS) do
        local s = GetItemClassInfo(path[1])
        if #path >= 2 then
            s = s.." > "..GetItemSubClassInfo(path[1], path[2])
        end
        if #path >= 3 then
            s = s.." > "..GetItemInventorySlotInfo(path[3])
        end
        s = RENAME_TABLE[s] or s
        table.insert(paths, {path=path, name=s})
    end

    return paths
end

function AuctipusDumpPaths()
    for i, path in ipairs(AuctipusGenPaths()) do
        print(path.name)
    end
end
